echo Installing - LibX 2.1...
sudo apt-get install -y - LibX 2.1
echo Installing - LibX 2.2...
sudo apt-get install -y - LibX 2.2
echo Installing - CoreLib 1.2...
sudo apt-get install -y - CoreLib 1.2
echo Installing - AIEngine 3.4...
sudo apt-get install -y - AIEngine 3.4
echo Installing - GraphV 5.0...
sudo apt-get install -y - GraphV 5.0
echo Installing AlphaSoft...
sudo apt-get install -y AlphaSoft
echo Installing BetaWare...
sudo apt-get install -y BetaWare
echo Installing DeltaApp...
sudo apt-get install -y DeltaApp
echo Installing EpsilonTool...
sudo apt-get install -y EpsilonTool
echo Installing GammaSuite...
sudo apt-get install -y GammaSuite